version: '3.1'

services:
  backend:
    build: .
    container_name: ecommerce-api
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - spring-postgres

  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=tolu
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myecommercedb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres:
